[package]
name = "static-site-generator"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.5.0"
pulldown-cmark = "0.13.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"
tera = "1.20.1"
