# Required
name: Hamdan Khan
bio: Software Engineer
email: hamdankhan212@gmail.com
description: Test

# Optional

baseurl: http://127.0.0.1:5500/public/

socials:
  github: https://github.com/hamdankhan
  twitter: https://twitter.com/hamdankhan
  linkedin: https://www.linkedin.com/in/hamdankhan
  website: https://hamdankhan.dev

# Experience

experience:
  - name: "Tech Company Inc."
    role: "Software Engineer"
    startdate: "May, 2023"
    enddate: "Present"
    location: "Remote"
    description: "Did absolutely nothing"

  - name: "Another Startup"
    role: "Software Engineer"
    startdate: "June, 2025"
    location: "Remote"
    description: "Did everything while i was there"

# Projects

projects:
  - name: "Test - Shell"
    description: "A minimal shell in C"
    link: https://google.com # optional
    github: "https://github.com/Hamdan-Khan/shell"

  - name: "Shell 2"
    description: "A minimal shell in C"
    github: "https://github.com/Hamdan-Khan/shell"

sideprojects:
  - name: "lorem ipsem"
    description: "A minimal shell in C"
    github: "https://github.com/Hamdan-Khan/shell"

  - name: "lorem ipsem"
    description: "A minimal shell in C"
    github: "https://github.com/Hamdan-Khan/shell"

extratest: un typed extra var
